version: "3.8"
services:
  backend:
    build:
      context: ./restapi
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./restapi:/app"
    ports:
      - "0.0.0.0:8000:8000"
    depends_on: 
      - postgres
      - pgadmin4
      - redis-server
  postgres:
    image: "postgres"
    restart: always
    environment: 
      - TZ=Asia/Kuala_Lumpur
      - POSTGRES_DB=tridatu
      - POSTGRES_USER=tridatu
      - POSTGRES_PASSWORD=123
  pgadmin4:
    image: "dpage/pgadmin4"
    ports: 
      - "0.0.0.0:5437:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=oman@tridatu.com
      - PGADMIN_DEFAULT_PASSWORD=123
  redis-server:
    image: "redis"
    sysctls:
      - net.core.somaxconn=511
