name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./restapi
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env file
        run: cp .env.example .env
      - name: Build the stack
        run: docker-compose up -d
      - name: Migrate Database
        run: bash scripts/migrate.sh
      - name: Test
        run: bash scripts/test.sh
      - name: Publish Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
